### ISSUE TITLE
Can't select an option from the dropdowns

### ISSUE THREAD

**Issue by quadcom** [adamsilverstein/modern-images-wp#13]
On the media settings page, I literally can't select an option in the dropdown other than the default which is already selected.

![image](https://user-images.githubusercontent.com/7085931/126424036-ff983189-d14f-4560-adcd-4540c8b9ab37.png)

WP 5.8

Cleared all server and browser cache. Made no difference.

**Comment by guugg** [comment]
It seems that the plug-in cannot be used yet, I can use it locally, but it won’t work when I install it online

**Comment by paroj** [comment]
the issue is this code:
https://github.com/adamsilverstein/modern-images-wp/blob/a66fe7a3d85a608334fe0bcf9b3132fbda50f4bc/src/Setting.php#L188-L196

If you got both imagick and libgd, but your imagick does not yet support webp, while libgd would it erroneously returns false

**Comment by quadcom** [comment]
My server actually doesn't have Imagemagick installed at all. GD is installed and does support WebP according to WP Health Info.

**Comment by devilcheng** [comment]
I can't choose AVIF and JPEG XL.

**Comment by adamsilverstein** [comment]
> I can't choose AVIF and JPEG XL.

Are those formats supported by your server? Check Site Health/Info to check.

> If you got both imagick and libgd, but your imagick does not yet support webp, while libgd would it erroneously returns false

@quadcom - The code checks which image engine your server uses: `$image_editor = _wp_image_editor_choose();` then checks if that image engine supports each format. Does this not work correctly for you? Can you paste the image support info from Site Health here please so I can see what your server setup looks like?

> It seems that the plug-in cannot be used yet, I can use it locally, but it won’t work when I install it online

@guugg - can you give it another try please? something was broken in a previous release.

**Comment by paroj** [comment]
for me its:

key | value
-- | --
ImageMagick supported file formats | 3FR,  AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3,  BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW,  CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1,  DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR,  FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY,  GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB,  ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX,  JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP,  MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG,  MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM,  PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF,  PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00,  PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB,  PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF,  RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR,  SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64,  TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF,  VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS,  XV, XWD, YCbCr, YCbCrA, YUV
GD version | bundled (2.1.0 compatible)
GD supported file formats | GIF, JPEG, PNG, WebP, BMP, XPM

**Comment by quadcom** [comment]
![image](https://user-images.githubusercontent.com/7085931/132717163-bb5a1070-a301-44fb-9dc7-619b513dd1bd.png)

Can't select anything in the dropdown
![image](https://user-images.githubusercontent.com/7085931/132717270-b392638e-8669-4fdc-94e0-c6101489bf0e.png)

**Comment by adamsilverstein** [comment]
Thanks @quadcom - I see what is happening here now - by default WordPress will use the first available image editor in its list, with Imagick being before GD in the default [list](https://github.com/WordPress/wordpress-develop/blob/e2feb7cf77603dcb0622b105377be7a37ffabf99/src/wp-includes/media.php#L3790). I also see now that I can pass a mime type to `_wp_image_editor_choose` that will change the behavior to choose the first editor that supports the mime type in question. 

I will push an update that should fix the dropdown for you.

**Comment by adamsilverstein** [comment]
@paroj - thanks for the details, appears to be the same issue from my previous comment. I will work on the fix and let you know when you can test.

**Comment by adamsilverstein** [comment]
@paroj  & @quadcom I improved support in https://github.com/adamsilverstein/modern-images-wp/pull/22 by passing the mime type when getting the image editor to use when checking support for each potential type.

Can you give that PR a test to see if you can now correctly select the WebP format from the dropdown?

ps. @quadcom I didn't see "ImageMagick supported file formats" in your screenshot, are you on WordPress 5.8? I wonder why that isn't showing.

**Comment by quadcom** [comment]
"ps. @quadcom I didn't see "ImageMagick supported file formats" in your screenshot, are you on WordPress 5.8? I wonder why that isn't showing."

I don't think it's installed/enabled by default by Runcloud

**Comment by quadcom** [comment]
I DL'd the zip from here and reinstalled. Showing the same version (1.0.2) and still shows the same behaviour.

**Comment by adamsilverstein** [comment]
@quadcom apologies for the confusion, you would have dow check out the PR to test. Here is a zip file that should work, you should see the version change to 1.0.3 when installing.

[modern-images-wp.zip](https://github.com/adamsilverstein/modern-images-wp/files/7140540/modern-images-wp.zip)

> I don't think it's installed/enabled by default by Runcloud

Its odd though because your screenshot does show Imagick installed, just not it's supported file types:

![image](https://user-images.githubusercontent.com/2676022/132782530-21f8e0d6-3065-4e31-b70b-d590b41c03e9.png)

Possibly something is wrong with how we are displaying these values in core.

**Comment by adamsilverstein** [comment]
@paroj & @quadcom I would appreciate your feedback here - I'd like to merge this soon and push a new release, please let me know if you see any issues and especially if this resolves the drop down not working for you.

**Comment by quadcom** [comment]
Sorry for the delay. I'm sorry to say that this is still not working in my case.

**Comment by paroj** [comment]
using the zip referenced here, I can select WebP in the dropdown
https://github.com/adamsilverstein/modern-images-wp/issues/13#issuecomment-916553909

However, no images seem to be actually converted. I examined existing images as well as uploading new ones. This should probably be tracked in a separate issue though.

**Comment by adamsilverstein** [comment]
@paroj Thanks for confirming this fixed the dropdown for you. Yes, let's address the images not being converted directly separately. One quick question - can you confirm you are able to upload WebP images in WordPress and it will correctly create sub sized WebP images for you? 

I'm guessing (and need to investigate) that the logic that switches sub sizes to WebP happens too late or is not recognized by the logic that decides which image editor to use when resizing a particular image. Can you test again with this filter (or download the gist zip and install as a mini plugin) - https://gist.github.com/adamsilverstein/c8b5d0145aeda7fe0a04e4573f2c7c32 - in this case we may need a small change in core to address. 

@quadcom ugh, I was hoping that would fix your case. Can you try the mini plugin above as well, that will set WordPress to prefer LibGD over Imagick which might help since you have both and I'm not sure your Imagick supports WebP. Also, can you confirm you see the plugin at 1.0.3 and are on WordPress 5.8?

**Comment by quadcom** [comment]
Hey Adam, I just wanted to let you know that I rebuilt my galleries on my site using my builder. I was using a third-party gallery plugin as the built-in galleries Oxygen builder has, has been a nightmare. Once I removed Foogallery from the site, your plugin started working again.

**Comment by adamsilverstein** [comment]
@paroj - I have created a proposed core patch that adds the image format adjustment to the place where the image engine is determined, if possible, please give this a try: https://github.com/WordPress/wordpress-develop/pull/1918/files

**Comment by adamsilverstein** [comment]
Should be fixed by https://core.trac.wordpress.org/ticket/54476

**Comment by adamsilverstein** [comment]
👋🏼 Hey @paroj & @quadcom we are working on a fix for this issue in https://core.trac.wordpress.org/ticket/54476 - would appreciate your help testing this if you are available - it only happens on certain environments (including yours), so verifying it fixes the issue for you would be helpful.
